# -*- coding: utf-8 -*-
"""cleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddSlgjOASgG4mjEhWB8wiQdJWkpJCwW3
"""

import pandas as pd

# Load dataset
df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Remove duplicate rows
df = df.drop_duplicates()

# Find numeric and categorical columns
num_cols = df.select_dtypes(include='number').columns
cat_cols = df.select_dtypes(include='object').columns

# Fill missing numeric values with median
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Fill missing categorical values with mode
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Standardize text columns
for col in cat_cols:
    df[col] = df[col].astype(str).str.title()

# Save cleaned dataset
df.to_excel("cleaned_dataset.xlsx", index=False)

print("Data cleaning completed successfully!")

from google.colab import files

uploaded = files.upload()

import os

os.listdir()

!ls

df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

import pandas as pd

df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")
df.head()

